name: forms_engine
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^5.0.2
  collection: ^1.16.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  reactive_forms: ^14.1.0
  digit_components: ^0.0.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  freezed: ^2.1.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  bloc_test: ^9.1.0

flutter: