name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  forms_engine: ^0.0.1
  digit_components: ^0.0.1
  auto_route: ^5.0.2
  collection: ^1.16.0
  reactive_forms: ^14.1.0
  dart_mappable: ^1.2.0
  flutter_keyboard_visibility: ^5.4.0
  material_design_icons_flutter: ^6.0.7096
  speech_to_text: ^6.1.1
  digit_firebase_services: ^0.0.1
  expandable: ^5.0.1
  qr_code_scanner: ^1.0.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  drift_dev: ^1.7.0
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  dart_mappable_builder: ^1.2.1
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  widgetbook: ^3.4.1

dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - ./

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  uses-material-design: true
