name: digit_entity_hooks
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  dart_mappable_builder: ^1.2.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.0
  dart_mappable: ^1.2.0
  mason: any
