name: health_campaigns_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  faker: ^2.0.0 # Library can be removed when no longer needed for fake data
  uuid: ^3.0.6
  intl: ^0.17.0
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  forms_engine:
    path: ./packages/forms_engine
  digit_components:
    path: ./packages/digit_ui_components
  auto_route: ^5.0.2
  flutter_bloc: ^8.1.1
  collection: ^1.16.0
  reactive_forms: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  drift_dev: ^1.7.0
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true