name: delivery
description: "This package enables health facility workers to deliver the resources to household and individual members.
version: 1.0.6"
version: 1.0.0
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/delivery
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  digit_ui_components: ^0.2.0
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  reactive_forms: ^17.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  dart_mappable: ^4.2.2
  drift: ^2.18.0
  auto_route: ^8.1.3
  digit_data_model: ^1.0.6+1
  collection: ^1.18.0
  dio: ^5.4.3+1
  location: ^6.0.2
  gs1_barcode_parser: ^1.0.5
  uuid: ^4.4.0
  recase: ^4.1.0
  pluto_grid: ^8.0.0
  digit_scanner: ^1.0.5+1
  fluttertoast: ^8.1.2
  overlay_builder: ^1.1.0
  digit_showcase: ^1.0.0
  stream_transform: ^2.1.0
  async: ^2.11.0
  formula_parser: ^2.0.1
  flutter_keyboard_visibility: ^5.4.1
  survey_form: ^1.0.1+3
  group_radio_button: ^1.3.0
  rename_flutter_project: ^1.0.2
  registration: ^1.0.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  drift_dev: ^2.14.1
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  build_runner: ^2.4.11
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  auto_route_generator: ^8.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/
