name: digit_components
description: Digit UI Design specification
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <=4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  horizontal_data_table: ^4.1.3
  location: ^4.4.0
  location_platform_interface: ^2.3.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  build_runner: ^2.2.1
  reactive_forms: ^14.1.0
  plugin_platform_interface: ^2.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.2
  flutter_spinkit: ^5.1.0
  reactive_flutter_typeahead: ^0.7.0
  flutter_typeahead: ^4.3.7
  overlay_builder: ^1.1.0
  easy_stepper: ^0.5.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.0
  freezed: ^2.2.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf

