name: digit_components
description: Digit UI Design specification Flutter widgets. Import this package by adding digit_components <latest> in respective pubspec.yaml dependencies.
version: 1.0.3
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/digit_components
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: '>=2.19.4 <3.9.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.0
  horizontal_data_table: ^4.1.3
  location: ^6.0.2
  location_platform_interface: ^4.0.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  build_runner: ^2.4.10
  reactive_forms: ^17.0.0
  plugin_platform_interface: ^2.1.3
  fluttertoast: ^8.2.6
  flutter_spinkit: ^5.1.0
  reactive_flutter_typeahead: ^2.1.1
  flutter_typeahead: ^4.6.2
  overlay_builder: ^1.1.0
  package_info_plus: ^8.0.0
  easy_stepper: ^0.8.5
  intl: ^0.19.0
  flutter_focus_watcher: ^2.0.0
  remove_emoji_input_formatter: ^0.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.4.0
  freezed: ^2.2.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.3

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf

