name: attendance_management
description: Digit UI attendance management specification - This tool is designed for tracking user attendance with customizable session counts per day.
version: 1.0.3-dev.1
homepage: "https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/attendance_management"
repository: "https://github.com/egovernments/health-campaign-field-worker-app"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digit_ui_components: ^0.0.2-dev.6
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  dart_mappable: ^4.2.2
  drift: ^2.18.0
  auto_route: ^8.1.3
  collection: ^1.18.0
  dio: ^5.4.3+1
  location: ^6.0.2
  fluttertoast: ^8.1.2
  overlay_builder: ^1.1.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  drift_db_viewer: ^2.0.0
  digit_data_model: ^1.0.5-dev.2
  reactive_forms: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  json_serializable: ^6.4.0
  freezed: ^2.5.2
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  auto_route_generator: 8.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/