name: attendance_management
description: Digit UI attendance management specification - This tool is designed for tracking user attendance with customizable session counts per day.
version: 1.0.2+4
homepage: "https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/attendance_management"
repository: "https://github.com/egovernments/health-campaign-field-worker-app"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digit_components: ^1.0.1+1
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  build_runner: ^2.2.1
  reactive_forms: ^14.1.0
  fluttertoast: ^8.1.2
  overlay_builder: ^1.1.0
  intl: ^0.18.0
  flutter_svg: ^2.0.8
  dart_mappable: ^4.2.0
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  drift_db_viewer: ^2.0.0
  auto_route: ^7.8.4
  digit_data_model: ^1.0.3+1
  connectivity_plus: ^5.0.2
  collection: ^1.16.0
  location: ^5.0.0
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.0
  freezed: ^2.2.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  drift_dev: ^2.14.1
  auto_route_generator: ^7.3.2

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/