name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ">=0.15.2 <= 0.18.0"
flutter:
  uses-material-design: true
