name: closed_household
description: This package enables health facility workers to mark household closed and update.
version: 1.0.4
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/develop/packages/closed_household
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digit_ui_components: ^0.0.2-dev.6
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  reactive_forms: ^17.0.0
  fluttertoast: ^8.1.2
  overlay_builder: ^1.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.8
  dart_mappable: ^4.2.0
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  drift_db_viewer: ^2.0.0
  uuid: ^4.4.0
  recase: ^4.1.0
  pluto_grid: ^8.0.0
  digit_scanner: ^1.0.4
  gs1_barcode_parser: ^1.0.5
  auto_route: ^8.1.3
  digit_data_model: ^1.0.5
  package_info_plus: ^8.0.0
  digit_showcase: ^1.0.0
  collection: ^1.16.0
  flutter_keyboard_visibility: ^5.4.0
  stream_transform: ^2.1.0
  async: ^2.11.0
  formula_parser: ^2.0.1
  registration_delivery: ^1.0.5
  location: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  drift_dev: ^2.14.1
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/