name: health_campaign_field_worker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.7.0

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  intl: ^0.19.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.11+1
  path_provider: ^2.1.3
  path: ^1.9.0
  digit_ui_components: ^0.2.0
  auto_route: ^8.3.0
  flutter_bloc: ^8.1.5
  collection: ^1.18.0
  reactive_forms: ^17.0.0
  location: ^6.0.2
  dart_mappable: ^4.2.2
  dio: ^5.4.3+1
  flutter_keyboard_visibility: ^5.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  nested: ^1.0.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  recase: ^4.1.0
  drift_db_viewer: ^2.1.0
  bloc_concurrency: ^0.2.5
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.3
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.3
  pretty_dio_logger: ^1.3.1
  pluto_grid: ^8.0.0
  flutter_portal: ^1.1.4
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2
  device_info_plus: ^9.1.2
  battery_plus: ^6.0.1
  workmanager: ^0.5.2
  digit_firebase_services: ^0.0.1
  package_info_plus: ^8.0.0
  expandable: ^5.0.1
  flutter_svg: ^2.0.10+1
  digit_showcase: ^1.0.2+1
  qr_flutter: ^4.1.0
  disk_space_update: ^0.0.2
  sync_service: ^1.0.1-dev.2-enumeration
  attendance_management: ^1.0.4+1
  digit_scanner: ^1.0.5
  inventory_management: ^1.0.5+1
  referral_reconciliation: ^1.0.5-dev.1-enumeration
  digit_data_model: ^1.0.7-dev.2-enumeration
  registration_delivery: ^1.0.7-dev.2-enumeration
  disable_battery_optimization: ^1.1.1
  digit_dss: ^1.0.4+1
  closed_household: ^1.0.5+1
  digit_location_tracker: ^1.0.0
  permission_handler: ^11.3.1
  survey_form: ^1.0.2-dev.1-enumeration
  complaints: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  drift_dev: ^2.18.0
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  hrk_flutter_test_batteries: ^0.8.0

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/icons/app_icon.png'
  min_sdk_android: 21

flutter:
  assets:
    - ./
    - assets/icons/svg/
    - assets/animated_json/
    - assets/images/
    - assets/audio/add.wav
    - assets/audio/buzzer.wav

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
  uses-material-design: true
