name: health_campaign_field_worker_app
description: A new Flutter project.
publish_to: "none"
version: 1.4.0+0

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6
  intl: ^0.18.0
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  digit_components: ^1.0.1
  auto_route: 
  flutter_bloc: ^8.1.1
  collection: ^1.16.0
  reactive_forms: ^14.1.0
  location: ^5.0.0
  dart_mappable: ^4.2.0
  dio: ^5.1.2
  flutter_keyboard_visibility: ^5.4.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  nested: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  recase: ^4.1.0
  drift_db_viewer: ^2.0.0
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.1.0
  fluttertoast: ^8.1.2
  flutter_secure_storage: ^9.0.0
  group_radio_button: ^1.3.0
  flutter_portal: ^1.1.3
  url_launcher: ^6.1.10
  connectivity_plus: ^5.0.2
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  pluto_grid: ^7.0.1
  speech_to_text: ^6.1.1
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.0
  device_info_plus: ^9.0.1
  battery_plus: ^5.0.2
  workmanager: ^0.5.1
  digit_firebase_services: ^0.0.1
  package_info_plus: ^5.0.1
  expandable: ^5.0.1
  flutter_svg: ^2.0.8
  digit_showcase: ^1.0.0
  audioplayers: ^5.2.0
  gs1_barcode_parser: ^1.0.5
  qr_flutter: ^4.1.0
  disk_space: ^0.2.1
  google_mlkit_barcode_scanning: ^0.10.0
  camera: ^0.10.5+7
  registration_delivery: ^1.0.3+3
  disable_battery_optimization: ^1.1.1
  closed_household: ^1.0.1+1
  digit_scanner: ^1.0.3+1
  digit_dss: ^1.0.2
  attendance_management: ^1.0.2+4
  inventory_management: ^1.0.3+4
  digit_data_model: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.4.7
  json_serializable: ^6.4.0
  drift_dev: ^2.14.1
  auto_route_generator: 
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder: ^4.2.0
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  hrk_flutter_test_batteries: ^0.8.0

dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - ./
    - assets/icons/svg/
    - ./assets/audio/add.wav
    - ./assets/audio/buzzer.wav

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
  uses-material-design: true
