name: health_campaign_field_worker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <=3.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6
  intl: ^0.17.0
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  forms_engine: ^0.0.1
  digit_components: ^0.0.1
  auto_route: ^5.0.2
  flutter_bloc: ^8.1.1
  collection: ^1.16.0
  reactive_forms: ^14.1.0
  location: ^4.4.0
  dart_mappable: ^1.2.0
  dio: ^4.0.6
  flutter_keyboard_visibility: ^5.4.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  nested: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  recase: ^4.1.0
  drift_db_viewer: ^1.0.3
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.1.0
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  drift_dev: ^1.7.0
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  dart_mappable_builder: ^1.2.1
  isar_generator: ^3.0.5

flutter:
  assets:
    - ./
  uses-material-design: true
