name: complaints
description: This package offers filing complaints features, allowing users to file complaints.
version: 1.0.1
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/referral_reconciliation
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digit_ui_components: ^0.0.2-dev.9
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  build_runner: ^2.2.1
  auto_route: ^8.1.3
  intl: ^0.19.0
  location: ^6.0.2
  isar: ^3.1.0+1
  digit_data_model: ^1.0.5
  dart_mappable: ^4.2.0
  group_radio_button: ^1.3.0
  reactive_forms: ^17.0.0
  recase: ^4.1.0
  flutter_svg: ^2.0.8
  path_provider: ^2.0.11
  drift: ^2.0.0
  dio: ^5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  dart_mappable_builder:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app/
      ref: master
      path: ./packages/dart_mappable_builder
  bloc_test: ^9.1.0
  mocktail: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/svg/
    - assets/animated_json/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
