name: digit_entity_hooks
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <=4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  dart_mappable_builder: 
       path: ../../../packages/dart_mappable_builder
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.0
  dart_mappable: ^4.2.0
  mason: any
  path: ^1.8.3
  recase: ^4.1.0
